all: hanoi1.pdf \
     hanoi2.pdf \
     hanoi3.pdf \
     hanoi4.pdf

hanoi1.pdf: hanoi1.svg
	inkscape --file=hanoi1.svg --without-gui --export-pdf=hanoi1.pdf

hanoi2.pdf: hanoi2.svg
	inkscape --file=hanoi2.svg --without-gui --export-pdf=hanoi2.pdf

hanoi3.pdf: hanoi3.svg
	inkscape --file=hanoi3.svg --without-gui --export-pdf=hanoi3.pdf


hanoi4.pdf: hanoi4.svg
	inkscape --file=hanoi4.svg --without-gui --export-pdf=hanoi4.pdf
